/**
 * Realistic ONDC B2B Wholesale Procurement Catalog
 * Enables rural merchants to discover wholesale prices directly from FPOs & manufacturers,
 * bypassing exploitative local middleman markups.
 */

export const WHOLESALE_CATALOG = [
  {
    id: 'ondc-atta-50kg',
    category: 'staples_kirana',
    categoryName: 'Kirana & Staples (दाल, आटा, तेल)',
    itemName: 'Chakki Fresh Wheat Atta (MP Sharbati)',
    itemNameHindi: 'चक्की फ्रेश शरबती गेहूं आटा',
    unit: '50 kg Bag',
    mrp: 1750,
    localMandiPrice: 1540,
    ondcB2BPrice: 1360,
    minOrderQty: 2,
    supplierName: 'Kashi Farmer Producer Co. (ONDC Agro Node)',
    supplierRating: 4.8,
    deliveryDays: 2,
    hubLocation: 'Varanasi Central Warehouse',
    leadTimeHours: 48,
    paymentTerms: 'UPI / 15-day Credit Line via TReDS'
  },
  {
    id: 'ondc-sugar-50kg',
    category: 'staples_kirana',
    categoryName: 'Kirana & Staples (दाल, आटा, तेल)',
    itemName: 'Refined White Sugar (M-30 Grade)',
    itemNameHindi: 'सफेद रिफाइंड चीनी (M-30)',
    unit: '50 kg Bag',
    mrp: 2200,
    localMandiPrice: 2050,
    ondcB2BPrice: 1840,
    minOrderQty: 2,
    supplierName: 'Basti Sahakari Chini Mills B2B Node',
    supplierRating: 4.9,
    deliveryDays: 2,
    hubLocation: 'Gorakhpur Buffer Depot',
    leadTimeHours: 48,
    paymentTerms: 'Instant UPI on Delivery'
  },
  {
    id: 'ondc-mustard-15l',
    category: 'staples_kirana',
    categoryName: 'Kirana & Staples (दाल, आटा, तेल)',
    itemName: 'Cold Pressed Kachi Ghani Mustard Oil',
    itemNameHindi: 'कच्ची घानी शुद्ध सरसों तेल',
    unit: '15 Litre Tin',
    mrp: 2350,
    localMandiPrice: 2180,
    ondcB2BPrice: 1920,
    minOrderQty: 2,
    supplierName: 'NAFED Oilseeds Federation ONDC Seller Node',
    supplierRating: 4.9,
    deliveryDays: 1,
    hubLocation: 'Chandauli Mandi Hub',
    leadTimeHours: 24,
    paymentTerms: 'UPI / Bank Transfer'
  },
  {
    id: 'ondc-toor-25kg',
    category: 'staples_kirana',
    categoryName: 'Kirana & Staples (दाल, आटा, तेल)',
    itemName: 'Unpolished Desi Arhar / Toor Dal Grade-A',
    itemNameHindi: 'देसी अरहर / तुअर दाल (अनपॉलिश्ड)',
    unit: '25 kg Bag',
    mrp: 4100,
    localMandiPrice: 3800,
    ondcB2BPrice: 3350,
    minOrderQty: 1,
    supplierName: 'Bundelkhand Pulse Farmers Producer Union',
    supplierRating: 4.7,
    deliveryDays: 3,
    hubLocation: 'Prayagraj Logistics Center',
    leadTimeHours: 72,
    paymentTerms: 'UPI / Working Capital Overdraft'
  },
  {
    id: 'ondc-salt-50x1kg',
    category: 'staples_kirana',
    categoryName: 'Kirana & Staples (दाल, आटा, तेल)',
    itemName: 'Iodized Vacuum Evaporated Table Salt',
    itemNameHindi: 'आयोडीन युक्त वैक्यूम नमक',
    unit: 'Carton (1 kg x 50 pkts)',
    mrp: 1400,
    localMandiPrice: 1150,
    ondcB2BPrice: 970,
    minOrderQty: 1,
    supplierName: 'Gujarat Salt Producers ONDC B2B Consortium',
    supplierRating: 4.8,
    deliveryDays: 2,
    hubLocation: 'Varanasi Railhead Stockyard',
    leadTimeHours: 48,
    paymentTerms: 'UPI / Cash on Delivery'
  },
  {
    id: 'ondc-tea-10kg',
    category: 'staples_kirana',
    categoryName: 'Kirana & Staples (दाल, आटा, तेल)',
    itemName: 'Kadak CTC Tea Leaf (Dooars Autumn Flush)',
    itemNameHindi: 'कड़क दानेदार चाय पत्ती (10kg)',
    unit: '10 kg Bulk Bag',
    mrp: 3200,
    localMandiPrice: 2850,
    ondcB2BPrice: 2420,
    minOrderQty: 1,
    supplierName: 'Small Tea Growers Federation of North Bengal',
    supplierRating: 4.8,
    deliveryDays: 3,
    hubLocation: 'Patna Regional Distribution Center',
    leadTimeHours: 72,
    paymentTerms: 'UPI / TReDS Trade Bill'
  },
  {
    id: 'ondc-soap-72pcs',
    category: 'fmcg_toiletries',
    categoryName: 'FMCG & Toiletries (साबुन, बिस्कुट, दैनिक वस्तुएं)',
    itemName: 'Germ Protection Bathing Soap (100g Bar)',
    itemNameHindi: 'कीटाणु सुरक्षा नहाने का साबुन',
    unit: 'Master Case (72 pcs)',
    mrp: 2520,
    localMandiPrice: 2280,
    ondcB2BPrice: 1980,
    minOrderQty: 1,
    supplierName: 'Bharat B2B FMCG Direct Hub',
    supplierRating: 4.7,
    deliveryDays: 2,
    hubLocation: 'Varanasi Industrial Area',
    leadTimeHours: 48,
    paymentTerms: 'UPI'
  },
  {
    id: 'ondc-biscuit-96pkts',
    category: 'fmcg_toiletries',
    categoryName: 'FMCG & Toiletries (साबुन, बिस्कुट, दैनिक वस्तुएं)',
    itemName: 'Everyday Glucose Energy Biscuits (80g)',
    itemNameHindi: 'ग्लूकोज ऊर्जा बिस्कुट (80g)',
    unit: 'Wholesale Carton (96 packs)',
    mrp: 960,
    localMandiPrice: 870,
    ondcB2BPrice: 770,
    minOrderQty: 2,
    supplierName: 'National Bakery Cooperative Network',
    supplierRating: 4.6,
    deliveryDays: 1,
    hubLocation: 'Varanasi Direct Depot',
    leadTimeHours: 24,
    paymentTerms: 'UPI / COD'
  },
  {
    id: 'ondc-thread-50spools',
    category: 'tailoring_apparel',
    categoryName: 'Tailoring & Textiles (सिलाई धागा व कपड़ा)',
    itemName: 'Spun Polyester High-Tenacity Thread (1000m)',
    itemNameHindi: 'पॉलिएस्टर सिलाई धागा रील (1000m)',
    unit: 'Box (50 Spools Assorted)',
    mrp: 1750,
    localMandiPrice: 1450,
    ondcB2BPrice: 1180,
    minOrderQty: 1,
    supplierName: 'Surat Textile Weavers ONDC Network',
    supplierRating: 4.9,
    deliveryDays: 3,
    hubLocation: 'Kanpur Hub',
    leadTimeHours: 72,
    paymentTerms: 'UPI'
  },
  {
    id: 'ondc-clay-50kg',
    category: 'handicraft_pottery',
    categoryName: 'Handicrafts & Artisans (कारीगर कच्चा माल)',
    itemName: 'Purified Fine Terracotta Clay Powder',
    itemNameHindi: 'शुद्ध टेराकोटा चिकनी मिट्टी चूर्ण',
    unit: '50 kg Bag',
    mrp: 950,
    localMandiPrice: 780,
    ondcB2BPrice: 590,
    minOrderQty: 2,
    supplierName: 'Nizamabad Black Pottery Artisans Guild',
    supplierRating: 4.9,
    deliveryDays: 2,
    hubLocation: 'Azamgarh Artisan Hub',
    leadTimeHours: 48,
    paymentTerms: 'UPI / Artisan Credit Card'
  }
];

export const WHOLESALE_CATEGORIES = [
  { id: 'all', name: 'All Categories (सभी वस्तुएं)' },
  { id: 'staples_kirana', name: 'Kirana & Staples (दाल, आटा, तेल)' },
  { id: 'fmcg_toiletries', name: 'FMCG & Toiletries (दैनिक वस्तुएं)' },
  { id: 'tailoring_apparel', name: 'Tailoring & Textiles (सिलाई)' },
  { id: 'handicraft_pottery', name: 'Handicrafts & Artisans (कारीगर)' }
];
